# Generated by Django 4.2 on 2023-04-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("ema", models.CharField(max_length=255, verbose_name="ЭМА")),
                ("empz", models.CharField(max_length=255, verbose_name="ЭМПЗ")),
                (
                    "patient_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="№",
                    ),
                ),
                ("ilness_history_num", models.CharField(verbose_name="ИБ №")),
                ("fio", models.CharField(max_length=1000, verbose_name="ФИО")),
            ],
            options={
                "verbose_name": "Пациента",
                "verbose_name_plural": "Пациентов",
            },
        ),
        migrations.CreateModel(
            name="UrinarySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("diurez", models.IntegerField(verbose_name="Суточный диурез")),
                ("infuzyy", models.IntegerField(verbose_name="Инфузии")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urin_collection",
                        to="backend.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись центральной нервной системы",
                "verbose_name_plural": "Записи центральной нервной системы",
            },
        ),
        migrations.CreateModel(
            name="RespiratorySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "system_type",
                    models.CharField(max_length=255, verbose_name="Тип дыхания"),
                ),
                (
                    "ventilation_type",
                    models.CharField(max_length=255, verbose_name="Режим вентиляции"),
                ),
                ("do", models.IntegerField(verbose_name="ДО")),
                ("chd", models.IntegerField(verbose_name="ЧД")),
                ("FiO2", models.IntegerField(verbose_name="FiO2 %")),
                ("peep", models.IntegerField(verbose_name="PEEP")),
                ("saturation", models.IntegerField(verbose_name="Сатурация %")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rs_collection",
                        to="backend.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись дыхательной системы",
                "verbose_name_plural": "Записи дыхательной системы",
            },
        ),
        migrations.CreateModel(
            name="MultiOrganFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("sofa", models.IntegerField(verbose_name="Баллы SOFA")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mof_collection",
                        to="backend.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись Полиорганной недостаточноти",
                "verbose_name_plural": "Записи Полиорганной недостаточноти",
            },
        ),
        migrations.CreateModel(
            name="CentralNervousSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "points",
                    models.IntegerField(
                        verbose_name="Результаты оценки по шкале ком Глазго"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=512, verbose_name="Описание результатов"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cns_collection",
                        to="backend.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись центральной нервной системы",
                "verbose_name_plural": "Записи центральной нервной системы",
            },
        ),
        migrations.CreateModel(
            name="CardiovascularSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("pulse", models.IntegerField(verbose_name="пульс в минуту")),
                ("chss", models.IntegerField(verbose_name="ЧСС в минуту")),
                ("ad_up", models.IntegerField(verbose_name="АД верх")),
                ("ad_down", models.IntegerField(verbose_name="АД низ")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cs_collection",
                        to="backend.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись сердечно-сосудистой системы ",
                "verbose_name_plural": "Записи сердечно-сосудистой системы",
            },
        ),
    ]
