# Generated by Django 4.2 on 2023-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="urinarysystem",
            options={
                "verbose_name": "Запись Мочевыделительной системы",
                "verbose_name_plural": "Записи Мочевыделительной системы",
            },
        ),
        migrations.AlterField(
            model_name="respiratorysystem",
            name="FiO2",
            field=models.IntegerField(blank=True, null=True, verbose_name="FiO2 %"),
        ),
        migrations.AlterField(
            model_name="respiratorysystem",
            name="do",
            field=models.IntegerField(blank=True, null=True, verbose_name="ДО"),
        ),
        migrations.AlterField(
            model_name="respiratorysystem",
            name="peep",
            field=models.IntegerField(blank=True, null=True, verbose_name="PEEP"),
        ),
        migrations.AlterField(
            model_name="respiratorysystem",
            name="ventilation_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Режим вентиляции"
            ),
        ),
    ]
